id: AF6BFFA0E
base_file: f4605.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.544997
  last_modified_at: 2022-06-19 17:35:01.545014
