id: AF6BFFA0E
base_file: f44FC.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.540564
  last_modified_at: 2022-06-19 17:35:01.540595
