id: AF6BFFA0E
base_file: fF277.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.552283
  last_modified_at: 2022-06-19 17:35:01.552286
