id: AF6BFFA0E
base_file: fFBAC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.553898
  last_modified_at: 2022-06-19 17:35:01.553901
