id: AF6BFFA0E
base_file: fA66C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.551088
  last_modified_at: 2022-06-19 17:35:01.551091
