id: AF6BFFA0E
base_file: f06CA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.527444
  last_modified_at: 2022-06-19 17:35:01.527453
