id: AF6BFFA0E
base_file: f443E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.531518
  last_modified_at: 2022-06-19 17:35:01.531526
