id: AF6BFFA0E
base_file: f48E9.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-19 17:35:01.548340
  last_modified_at: 2022-06-19 17:35:01.548348
